### ISSUE TITLE
خطا در هنگام صادر کردن به HTML 

### ISSUE THREAD

**Issue by rastikerdar** [ilius/starcal#21]
هنگام کلیک اتفاقی نمی افتد اما در ترمینال چنین می نویسد:

```
Exporting to html file "/home/zz/calendar-1394-11.html"
Traceback (most recent call last):
  File "/usr/share/starcal3/scal3/ui_gtk/export.py", line 128, in save
    exportToHtml(path, months, title)
  File "/usr/share/starcal3/scal3/export.py", line 188, in exportToHtml
    text += pluginsText
TypeError: can't concat bytes to str

```

**Comment by ilius** [comment]
ممنون از گزارش
