### ISSUE TITLE
عدم اجرا شدن در آرچ 

### ISSUE THREAD

**Issue by behroozramezani** [ilius/starcal#26]
برنامه در توزیع ارچ اجرا نمیشه خروجی ترمینال 
```bash
[behrooz@Lenovo-G500 starcal]$ starcal3
failed to load json file /usr/share/starcal3/conf/lang/fa_IR.UTF-8.json
Traceback (most recent call last):
  File "/usr/share/starcal3/scal3/ui_gtk/starcal.py", line 52, in <module>
    from scal3 import core
  File "/usr/share/starcal3/scal3/core.py", line 38, in <module>
    from scal3 import locale_man
  File "/usr/share/starcal3/scal3/locale_man.py", line 187, in <module>
    raise e
  File "/usr/share/starcal3/scal3/locale_man.py", line 184, in <module>
    data = jsonToData(open(fpath).read())
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd9 in position 71: ordinal not in range(128)
```

**Comment by ilius** [comment]
لطفاً تست کنید

**Comment by behroozramezani** [comment]
خوب من بتدا نسخه جاری را پاک کردم و دوباره نصب کردم اینم کل مراحل نصب و خروجی برنامه در ترینال متاسفانه برنامه هنوز اجرا نمیشه
```bash
[behrooz@Lenovo-G500 ~]$ git clone https://github.com/ilius/starcal.git
Cloning into 'starcal'...
remote: Counting objects: 16815, done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 16815 (delta 27), reused 0 (delta 0), pack-reused 16764
Receiving objects: 100% (16815/16815), 7.34 MiB | 922.00 KiB/s, done.
Resolving deltas: 100% (12373/12373), done.
Checking connectivity... done.
[behrooz@Lenovo-G500 ~]$ cd starcal/
[behrooz@Lenovo-G500 starcal]$ bash install-archlinux 
==> Making package: starcal3 3.0.2-1 (Thu Jul 21 16:22:41 IRDT 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
==> Extracting sources...
==> Entering fakeroot environment...
==> Starting package()...
ERROR: ld.so: object 'libfakeroot.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
find: 'scal3': No such file or directory
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> Creating package "starcal3"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: starcal3 3.0.2-1 (Thu Jul 21 16:22:44 IRDT 2016)
==> Installing package starcal3 with pacman -U...
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) starcal3-3.0.2-1

Total Installed Size:  1.88 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                             [####################################################] 100%
(1/1) checking package integrity                                                           [####################################################] 100%
(1/1) loading package files                                                                [####################################################] 100%
(1/1) checking for file conflicts                                                          [####################################################] 100%
(1/1) checking available disk space                                                        [####################################################] 100%
:: Processing package changes...
(1/1) installing starcal3                                                                  [####################################################] 100%
Optional dependencies for starcal3
    python-dateutil [installed]
    python-igraph
:: Running post-transaction hooks...
(1/2) Updating icon theme caches...
(2/2) Updating the desktop file MIME type cache...
Package installed and copied into /home/behrooz/starcal directory
[behrooz@Lenovo-G500 starcal]$ starcal3
Traceback (most recent call last):
  File "/usr/share/starcal3/scal3/ui_gtk/starcal.py", line 52, in <module>
    from scal3 import core
  File "/usr/share/starcal3/scal3/core.py", line 578, in <module>
    licenseText = open('%s/license'%rootDir).read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 69: ordinal not in range(128)
```

**Comment by ilius** [comment]
لطفاً دوباره تست کنید

**Comment by behroozramezani** [comment]
خوب بعد از آپدیت اخری مشکل حل شد و برنامه اجرا شد اما موقعی که در ترمینال اجراش کردم با اینکه اجرا شد این ارور را میده 
```bash
[behrooz@Lenovo-G500 starcal]$ starcal3
failed to write lock file /home/behrooz/.starcal3/event/lock.json: [Errno 2] No such file or directory: '/home/behrooz/.starcal3/event/lock.json'
/usr/share/starcal3/scal3/ui_gtk/drawing.py:31: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository.PangoCairo import show_layout
"winTaskbar", "False", "True"
/usr/share/starcal3/scal3/ui_gtk/drawing.py:31: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository.PangoCairo import show_layout
```

**Comment by ilius** [comment]
برطرف شد
