### ISSUE TITLE
مشکل تنظیم ماه‌های قمری

### ISSUE THREAD

**Issue by HassanHeydariNasab** [ilius/starcal#38]
سلام
پس از تنظیم شعبان از ۲۹ به ۳۰ و رمضان از ۳۰ به ۲۹ برنامه درخواست بازآغازی داد و دیگر اجرا نشد.
پس از تغییر  
`hijriUseDB`
در
`hijri.json`
 به
 `false`
!مشکل موقتاً حل شد
اوبونتو ۱۶.۰۴
3.0.6

**Comment by ilius** [comment]
سلام
از کدوم ورژن استفاده می‌کنید؟
لطفاً برنامه رو با دستور
starcal3
توی ترمینال اجرا کنید و خروجی/ارور ترمینال رو بگذارید

**Comment by HassanHeydariNasab** [comment]
```
starcal3
praytimes: onCurrentDateChange (2017, 6, 14)
toPreAzanSec=1675.0
toAzanSecs=1795.0
toPreAzanSec=28068.0
toAzanSecs=28188.0
Traceback (most recent call last):
  File "/usr/share/starcal3/scal3/ui.py", line 362, in getCell
    return self.jdCells[jd]
KeyError: 2457919

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/starcal3/scal3/ui_gtk/starcal.py", line 1075, in <module>
    sys.exit(main())
  File "/usr/share/starcal3/scal3/ui_gtk/starcal.py", line 1053, in main
    ui.init()
  File "/usr/share/starcal3/scal3/ui.py", line 533, in init
    todayCell = cell = cellCache.getTodayCell() ## FIXME
  File "/usr/share/starcal3/scal3/ui.py", line 371, in <lambda>
    getTodayCell = lambda self: self.getCell(core.getCurrentJd())
  File "/usr/share/starcal3/scal3/ui.py", line 364, in getCell
    return self.buildCell(jd)
  File "/usr/share/starcal3/scal3/ui.py", line 373, in buildCell
    localCell = Cell(jd)
  File "/usr/share/starcal3/scal3/ui.py", line 290, in __init__
    for mode in range(len(calTypes))
  File "/usr/share/starcal3/scal3/ui.py", line 290, in <listcomp>
    for mode in range(len(calTypes))
  File "/usr/share/starcal3/scal3/cal_types/__init__.py", line 124, in <lambda>
    jd_to = lambda jd, target: modules[target].jd_to(jd)
  File "/usr/share/starcal3/scal3/cal_types/hijri.py", line 208, in jd_to
    date = monthDb.getDateFromJd(jd)
  File "/usr/share/starcal3/scal3/cal_types/hijri.py", line 158, in getDateFromJd
    monthLen = self.monthLenByYm[ym]
KeyError: 17148
^CException ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by ilius** [comment]
لطفاً این دستور رو بزنید
rm ~/.starcal3/hijri-monthes.json
و بعد دوباره از پنجرهٔ تنظیم ماه‌های قمری تغییرات رو اعمال و تست کنید

**Comment by HassanHeydariNasab** [comment]
بعد از
 rm ~/.starcal3/hijri-monthes.json
یک کم باهاش ور رفتم و یک خطایی داد و محتویات تقویم غیب شد.
اون خطی که تغییر دادید رو برای خودم تغییر دادم و دوباره
 rm ~/.starcal3/hijri-monthes.json
زدم و حل شد.

**Comment by airani** [comment]
این مشکل کماکان در نسخه `3.2.0‍` وجود داره

```
Local Time Zone: Asia/Tehran
registerConsumer: IntegatedWindowList
lock file /home/foo/.starcal3/event/lock.json: pid 70205 does not exist
Scanning last_ids took 0.000 seconds, LastIds(event=0, group=3, account=0)
/usr/bin/starcal3: line 2: 70406 Segmentation fault      /usr/bin/python3 /usr/share/starcal3/scal3/ui_gtk/starcal-main.py "$@"
```
