### ISSUE TITLE
BSON error

### ISSUE THREAD

**Issue by mohammad-h-fathi** [ilius/starcal#45]
Ive install BSON from both python-bson package, and pip. but starcal is not starting yet.
`Traceback (most recent call last):
  File "/usr/share/starcal3/scal3/ui_gtk/starcal.py", line 52, in <module>
    from scal3 import core
  File "/usr/share/starcal3/scal3/core.py", line 38, in <module>
    from scal3 import locale_man
  File "/usr/share/starcal3/scal3/locale_man.py", line 31, in <module>
    from scal3.s_object import JsonSObj
  File "/usr/share/starcal3/scal3/s_object.py", line 7, in <module>
    from bson import BSON
ImportError: cannot import name 'BSON'
`

**Comment by ilius** [comment]
python-bson is for python2. (Unless you use Arch)
And your pip is probably pip2 (python2)
Install python3-bson or python3-mongo, or use pip3
