### ISSUE TITLE
خطا هنگام اجرا روی Archlinux

### ISSUE THREAD

**Issue by sparse91** [ilius/starcal#54]
سلام
من نسخه aur رو نصب کردم. اگر مشکلی داره بگید تا بسته شو درست کنم
ممنون
```
Traceback (most recent call last):
  File "/usr/share/starcal3/scal3/ui.py", line 362, in getCell
    return self.jdCells[jd]
KeyError: 2458524

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/starcal3/scal3/event_search_tree.py", line 165, in searchStep
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/starcal3/scal3/ui_gtk/starcal.py", line 1075, in <module>
    sys.exit(main())
  File "/usr/share/starcal3/scal3/ui_gtk/starcal.py", line 1053, in main
    ui.init()
  File "/usr/share/starcal3/scal3/ui.py", line 533, in init
    todayCell = cell = cellCache.getTodayCell() ## FIXME
  File "/usr/share/starcal3/scal3/ui.py", line 371, in <lambda>
    getTodayCell = lambda self: self.getCell(core.getCurrentJd())
  File "/usr/share/starcal3/scal3/ui.py", line 364, in getCell
    return self.buildCell(jd)
  File "/usr/share/starcal3/scal3/ui.py", line 373, in buildCell
    localCell = Cell(jd)
  File "/usr/share/starcal3/scal3/ui.py", line 310, in __init__
    self.eventsData = event_lib.getDayOccurrenceData(jd, eventGroups)## here? FIXME
  File "/usr/share/starcal3/scal3/event_lib.py", line 4155, in getDayOccurrenceData
    for epoch0, epoch1, eid, odt in group.occur.search(getEpochFromJd(curJd), getEpochFromJd(curJd+1)):
  File "/usr/share/starcal3/scal3/event_search_tree.py", line 185, in search
    for mt, dt, eid in self.searchStep(self.root, t0, t1):
RuntimeError: generator raised StopIteration
```

**Comment by ilius** [comment]
سلام
آیا از آخرین کد برنچ مستر استفاده می‌کنه؟
اگر نه،  آپدیت کنید به آخرین کد مستر
